version: "3"

services:
  ps-shop-mysql:
    image: mysql:5.7
    container_name: local-mysql-prestashop
    networks: prestashop-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3307:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password


  ps-shop-prestashop:
    image: prestashop/prestashop
    container_name: local-prestashop
    networks: prestashop-net
    depends_on:
        - local-mysql-prestashop
    environment:
        - DB_SERVER=local-mysql-prestashop
    ports:
        - "8082:80"



